### ISSUE TITLE
does not work with zsh-users/zsh-syntax-highlighting

### ISSUE THREAD

**Issue by zUnixorn** [zpm-zsh/zpm#46]
when adding `zpm load @github/zsh-users/zsh-syntax-highlighting,source:zsh-syntax-highlighting.zsh` to the .zshrc I get this error: 

```
(anon):43: no such file or directory: /home/jonas/.version
(anon):44: no such file or directory: /home/jonas/.revision-hash
zsh-syntax-highlighting: highlighters directory '/home/jonas/highlighters' not found.
zsh-syntax-highlighting: failed loading highlighters, exiting.
```

When I type `zpm clean` it works again, but when I start a new shell its throwing this error again. I tried adding `path:/highlighters` but that didn't change anything.

Do you know what i'd need to change to get it working with zpm?

plugin source: https://github.com/zsh-users/zsh-syntax-highlighting/

**Comment by grigorii-horos** [comment]
Please, update zpm first

**Comment by zUnixorn** [comment]
I just downloaded zpm when posting the issue, so it is up-to-date. And doing `zpm upgrade` also didn't help.

**Comment by grigorii-horos** [comment]
Hm... Very strange. I just tested in clean env,  and all works great. 
![image](https://user-images.githubusercontent.com/4980269/155390864-0f426b8e-5a61-426b-9472-c93416f59948.png)

**Comment by grigorii-horos** [comment]
![image](https://user-images.githubusercontent.com/4980269/155390953-fcf0dc16-f004-4551-8d3f-8ab8fd1b6ba8.png)

**Comment by zUnixorn** [comment]
I tried it on three different distros and in every test I first ran `exec zsh -d -f` and then
```
if [[ ! -f ~/.local/share/zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.local/share/zpm
fi
source ~/.local/share/zpm/zpm.zsh

zpm @github/zsh-users/zsh-syntax-highlighting,source:zsh-syntax-highlighting.zsh
```
and I got the same error on all three distros.

I am unsure what could be the cause of these different results, `zsh -d -f` should yield a clean enviornment so that shouldn't be the cause.

**Comment by zUnixorn** [comment]
did you restart the shell and tried it again, because when I stay in the same session everything works fine. But when I close it I get that error, doing `zpm clean` and the `zpm load` fixes it for the current session, restarting it makes the error come up again...

**Comment by jqhr** [comment]
@grigorii-horos @zUnixorn 
I also encountered this problem.That problem is due to /tmp/zsh-1000. The cache directory.
I add
```zsh
[ -d /tmp/zsh-1000/ ] && rm -rf /tmp/zsh-1000/*

```
before source zpm/zpm.zsh.
And it works

**Comment by avently** [comment]
@grigorii-horos have the same problem with some plugins, Could you, please, take a look if you can fix the issues with them?

```
zpm load b4b4r07/enhancd
Result after opening a new shell:
__enhancd::init::init:5: no matches found: /tmp/zsh-1000/src/*.sh
```

```
zpm load zsh-users/zsh-history-substring-search
Result after opening a new shell:
(anon):source:3: No such file or directory: /home/user/zsh-history-substring-search.zsh
```
With other plugin managers they work fine.

**Comment by grigorii-horos** [comment]
Fixed in main

**Comment by maxenced** [comment]
This still occurs with fresh zpm install (commit 926ce79a14edf3b6fe64a1be873543c58ba8782a) : 
```
(anon):43: aucun fichier ou dossier de ce nom: /home/maxence/.version
(anon):44: aucun fichier ou dossier de ce nom: /home/maxence/.revision-hash
zsh-syntax-highlighting: highlighters directory '/home/maxence/highlighters' not found.
zsh-syntax-highlighting: failed loading highlighters, exiting.
``` 

deleting the /tmp/zsh-1000 directory help for the first run after it, but all the next one fails

**Comment by fyrak1s** [comment]
Hi, I'm using ZPM for the first time and I am getting this as well.

Tested this on a fresh setup!

> When I type zpm clean it works again, but when I start a new shell its throwing this error again.

Exactly the same here. It works in a running session. But not in a fresh one.

**Comment by grigorii-horos** [comment]
Reopening this in practice — the earlier "Fixed in main" did not hold, and the reports from @maxenced and @fyrak1s are correct. Here is the actual root cause and a fix: #70.

### Root cause

The guess earlier in this thread (that the plugin overwrites `$0` later) was half right. The specific reason is that current zsh-syntax-highlighting (0.8.x) does **not** use the `ZERO`-aware PMSPEC snippet at all. Line 39 is:

```zsh
# Set $0 to the expected value, regardless of functionargzero.
0=${(%):-%N}
```

That is an *unconditional* overwrite with prompt-escape `%N` — "the name of the script, sourced file, or shell function currently executing".

ZPM's cache inlined each plugin's body into an **anonymous** function:

```zsh
(){
0='/path/to/zsh-syntax-highlighting.zsh'
<entire plugin body copied in>
}
```

Inside an anonymous function `%N` is the literal string `(anon)`. It has no slash, so zsh expands `${0:A:h}` to `$PWD` — which is why the paths in the error messages are your home directory:

```
(anon):43: no such file or directory: /home/jonas/.version
zsh-syntax-highlighting: highlighters directory '/home/jonas/highlighters' not found.
```

Setting `0=` or `ZERO` before the body cannot help, because the plugin throws both away.

### Why `zpm clean` "fixed" it for one shell

Because the cold and warm paths did different things:

| | cold start (`@zpm-source`) | warm start (from cache) |
|---|---|---|
| mechanism | `source <file>` | inlined into `(){ … }` |
| `$0`, `%N` | `<file>` | `(anon)` |
| `%x` | `<file>` | `<cache file>` |
| `ZERO` | set | unset |

The first shell after `zpm clean` ran a real `source`, so it worked. Every shell after that read the cache, so it broke. That also explains @jqhr's `rm -rf /tmp/zsh-1000` workaround — it forces the cold path on every start.

### Other plugins in this thread

- @avently's `zsh-history-substring-search` failure (`No such file or directory: /home/user/zsh-history-substring-search.zsh`) is the same `%N` bug — its `.plugin.zsh` does `source ${0:A:h}/…`, and `${0:A:h}` became `$PWD`. Fixed.
- @avently's `enhancd` failure (`no matches found: /tmp/zsh-1000/src/*.sh`) is the `%x` variant: `/tmp/zsh-1000` is the *cache file's* directory. Also fixed, because the cache now sources the real file.
- @bw-matthew's diagnosis was closest to correct — thank you, it was the right thread to pull.

### The fix

The cache now emits, per plugin:

```zsh
(){ local ZERO=/path/to/plugin.zsh; source /path/to/plugin.zsh; }
```

`source` gives the plugin its own `$0` / `%N` / `%x` / `ZERO`; the anonymous function preserves the scope it had before, so a plugin starting with `emulate -L zsh` still cannot leak shell options into your session.

Startup time is unchanged (9.01 ms vs 8.98 ms median over 60 runs) — plugin files are already byte-compiled individually, so inlining them into one file bought nothing.

Verified against real `zsh-users/zsh-syntax-highlighting` and `zsh-users/zsh-history-substring-search` in a throwaway `$HOME`: three consecutive warm starts, no errors, `ZSH_HIGHLIGHT_VERSION` correctly populated. Without the patch, same sandbox, same commands: the four errors above. Regression tests were added that start a fresh `zsh` against the generated cache, so this cannot silently come back.

Sorry it took this long. If you are hitting this, testing #70 before it merges would be welcome.
